docs/deployment/guide.md, docs/file-formats/election-creation-json.md
=> Timezone support

docs/file-formats/election-creation-json.md
* documenting publicCandidates election option
* updating doc
=> documenting publicCandidates election option

docs/general/concepts/concepts.md, docs/general/contribute/contribute.md, docs/general/reference/reference.md
- Removing Concepts TODO item
- reorder sidebar
=> small fixes

docs/general/guides/parent-and-children-elections/parent-and-children-elections.md
Automate filling in election IDs. If the election ID in the Election JSON is negative, replace it with new Election IDs.
=> Election IDs automation

docs/general/guides/parent-and-children-elections/parent-and-children-elections.md
voters field for election automation
=> Support census/voters on election id automation

docs/general/reference/election-creation-json.md
Add documentation for presentation field `anchor_continue_btn_to_bottom`.
=> Always fix continue button to bottom

docs/general/contribute/release-howto.md
Parent issue: https://github.com/sequentech/meta/issues/67
=> Update release how-to for comprehensive releases

docs/general/reference/election-creation-json.md
Parent issue: https://github.com/sequentech/epi/issues/114
=> Alternative Auth methods support

docs/general/guides/write-ins/write-ins.md, docs/general/reference/election-creation-json.md
Parent issue: https://github.com/sequentech/epi/issues/119
=> ✨dynamic position of invalid vote option

docs/general/guides/write-ins/write-ins.md, docs/general/reference/election-creation-json.md
Parent issue: https://github.com/sequentech/epi/issues/119
=> ✨dynamic position of invalid vote option (#119)

docs/general/reference/election-creation-json.md
Parent issue: https://github.com/sequentech/meta/issues/122
=> ✨ Multilingualism

docs/general/guides/deployment/deployment.md
Parent issue: https://github.com/sequentech/meta/issues/119
=> 🐞 add census data second batch will not be executed (#124)

docs/general/reference/election-creation-json.md
Parent issue: https://github.com/sequentech/meta/issues/151
=> ✨ Visualization of write-in fields in Review

docs/general/reference/election-creation-json.md
Parent issue: https://github.com/sequentech/meta/issues/219
=> 🐞 alternative auth method json param

docs/general/reference/reference.md, docs/general/reference/user-permissions.md
Parent issue: https://github.com/sequentech/meta/issues/127
=> ✨ Role-based login for election manager

docs/general/reference/election-creation-json.md
Parent issue: https://github.com/sequentech/meta/issues/126
=> ✨ Support search/filter candidates feature in voting booth

docs/general/reference/election-creation-json.md
Parent issue: https://github.com/sequentech/epi/issues/112
=> ✨ Voting-booth: Improve election info in the ballot ticket PDF for parent-children elections

docs/general/reference/election-creation-json.md
Parent issue: https://github.com/sequentech/meta/issues/306
=> ✨ Select languages per election

docs/general/reference/election-creation-json.md
Parent issue: https://github.com/sequentech/meta/issues/224
=> ✨ Voting Booth: Security confirmation checkbox support

docs/general/reference/election-creation-json.md
Parent issue: https://github.com/sequentech/meta/issues/678
=> 🐞 question-extra-invalid_vote_policy doesn't work

docs/general/guides/deployment/deployment.md
Parent issue: https://github.com/sequentech/epi/issues/36
=> ✨ Check if the authorities are online

docs/general/guides/deployment/deployment.md
Parent issue: https://github.com/sequentech/epi/issues/36
=> ✨ Check if the authorities are online (#147)
